apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.mainAppname }}
  labels:
    app: {{ .Values.mainAppname }}
spec: 
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 20 
  selector: 
    matchLabels: 
      app: {{ .Values.mainAppname }} 
  template : 
    metadata: 
      labels: 
        app: {{ .Values.mainAppname }} 
    spec: 
      containers: 
      - name: {{ .Values.mainAppname }} 
        image: "{{ .Values.mainAppnameimage }}:{{ .Values.mainAppnameimagetag }}"
        ports:
        - containerPort: 8080
        env:
            - name: DB_HOST
              value: "127.0.0.1"
            - name: DB_PORT
              value: "3306" 
            - name: MYSQL_USER
              value: {{ .Values.appUsername }}
            - name: MYSQL_PASS
              value: {{ .Values.appUserpassword }}
            - name: DB_NAME
              value: {{ .Values.AppDatabase }}
            - name: SPRING_PROFILES_ACTIVE 
              value: mysql       
            - name: DATASOURCE_INIT_MODE
              value: always
      - name: {{ .Values.sidecarAppname }}
        image: "{{ .Values.sidecarAppnameimage }}:{{ .Values.sidecarAppnameimagetag }}" 
        command:
          - "/cloud_sql_proxy"
          - "-log_debug_stdout"
          - "-instances=or2-msq-epm-cedu-t1iylu:us-central1:my-instance=tcp:3306" 
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu:    "1"