apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.mainAppname }}
  labels:
    app: {{ .Values.mainAppname }}
spec: 
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: 20 
  selector: 
    matchLabels: 
      app: {{ .Values.mainAppname }} 
  template : 
    metadata: 
      labels: 
        app: {{ .Values.mainAppname }} 
    spec: 
      containers: 
      - name: {{ .Values.mainAppname }} 
        image: "{{ .Values.mainAppnameimage }}:{{ .Values.mainAppnameimagetag }}"
        ports:
        - containerPort: {{ .Values.mainAppcontainerPort }}
        env:
            - name: DB_HOST
              value: {{ .Values.mainAppDatabasehost }}
            - name: DB_PORT
              value: {{ .Values.mainAppDatabasePort }} 
            - name: MYSQL_USER
              value: {{ .Values.appUsername }}
            - name: MYSQL_PASS
              value: {{ .Values.appUserpassword }}
            - name: DB_NAME
              value: {{ .Values.appDatabase }}
            - name: SPRING_PROFILES_ACTIVE 
              value: {{ .Values.mainAppSpringProfile }}       
            - name: DATASOURCE_INIT_MODE
              value: {{ .Values.mainAppDatasourceMode }}
      - name: {{ .Values.sidecarAppname }}
        image: "{{ .Values.sidecarAppnameimage }}:{{ .Values.sidecarAppnameimagetag }}" 
        command:
          - "/cloud_sql_proxy"
          - "-log_debug_stdout"
          - "-instances={{ .Values.sidecarAppConnection }}" 
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: "2Gi"
            cpu:    "1"