apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name: {{ .Values.mainAppname | default "spring-petclinic" | quote }}
  labels:
    app: {{ .Values.mainAppname | default "spring-petclinic" | quote }}
spec: 
  replicas: {{ .Values.replicaCount }}
  minReadySeconds: {{ .Values.minReadySeconds }} 
  selector: 
    matchLabels: 
      app: {{ .Values.mainAppname | default "spring-petclinic" | quote }} 
  template : 
    metadata: 
      labels: 
        app: {{ .Values.mainAppname | default "spring-petclinic" | quote }} 
    spec: 
      containers: 
      - name: {{ .Values.mainAppname | default "spring-petclinic" | quote }} 
        image: "{{ .Values.mainAppnameimage }}:{{ .Values.mainAppnameimagetag }}"
        ports:
        - containerPort: {{ .Values.mainAppcontainerPort }}
        env:
            - name: DB_HOST
              value: {{ .Values.mainAppcontainerDBHost }}
            - name: DB_PORT
              value: {{ .Values.mainAppcontainerDBPort }} 
            - name: MYSQL_USER
              value: {{ .Values.appUsername }}
            - name: MYSQL_PASS
              value: {{ .Values.appUserpassword }}
            - name: DB_NAME
              value: {{ .Values.appDatabase }}
            - name: SPRING_PROFILES_ACTIVE 
              value: {{ .Values.mainAppSpringProfile }}       
            - name: DATASOURCE_INIT_MODE
              value: {{ .Values.mainAppDatasourceMode }}
      - name: {{ .Values.sidecarAppname }}
        image: "{{ .Values.sidecarAppnameimage }}:{{ .Values.sidecarAppnameimagetag }}" 
        command:
          - "/cloud_sql_proxy"
          - "-log_debug_stdout"
          - "-instances={{ .Values.sidecarAppConnection }}" 
        securityContext:
          runAsNonRoot: true
        resources:
          requests:
            memory: {{ .Values.sidecarAppnameMemory }}
            cpu: {{ .Values.sidecarAppnameCpu }}