apiVersion: v1
kind: Secret
metadata:
   name: {{ .Values.secretName }} 
type: Opaque
data:
  database: {{ default "" .Values.app.database | b64enc | quote }}
  mysql-user: {{ default "" .Values.app.username | b64enc | quote }}
  mysql-password: {{ default "" app.userpassword | b64enc | quote }}