---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.main-app-name }}
spec:
  ports:
    - name: http
      port: {{ .Values.service-port }}
      targetPort: {{ .Values.service-targetPort }}
  selector:
    app: {{ .Values.main-app-name }}
  type:  {{ .Values.service-type }}