apiVersion: v1
kind: Secret
metadata:
   name: {{ .Values.secretName }} 
type: Opaque
data:
  database: {{ default "" .Values.appDatabase }}
  mysql-user: {{ default "" .Values.appUsername }}
  mysql-password: {{ default "" .Values.appUserpassword }}