apiVersion: v1
kind: Secret
metadata:
   name: {{ .Values.secretName }} 
type: Opaque
data:
  database: {{ default "" .Values.appDatabase | b64enc | quote }}
  mysql-user: {{ default "" .Values.appUsername | b64enc | quote }}
  mysql-password: {{ default "" appUserpassword | b64enc | quote }}