apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mainAppname }}
spec:
  ports:
    - name: http
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
  selector:
    app: {{ .Values.mainAppname }}
  type:  {{ .Values.serviceType }}