apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mainAppname | default "spring-petclinic" | quote }}
spec:
  ports:
    - name: {{ .Values.servicePortType }}
      port: {{ .Values.servicePort }}
      targetPort: {{ .Values.serviceTargetPort }}
  selector:
    app: {{ .Values.mainAppname | default "spring-petclinic" | quote }}
  type:  {{ .Values.serviceType }}