secretName: db-credentials
app.database: cGV0Y2xpbmlj
app.username: cGV0Y2xpbmlj
app.userpassword: cGV0Y2xpbmlj
main-app-name: spring-petclinic
main-app-name-image: us-central1-docker.pkg.dev/or2-msq-epm-cedu-t1iylu/petclinic-repo-halka/petclinic-app
main-app-name-image-tag: latest
sidecar-app-name: cloud-sql-proxy
sidecar-app-name-image: gcr.io/cloudsql-docker/gce-proxy
sidecar-app-name-image-tag: 1.28.0
replicaCount: 1
service-port: 80
service-targetPort: 8080
service-type: LoadBalancer