appDatabase: petclinic
appUsername: petclinic
appUserpassword: petclinic
mainAppname: spring-petclinic
mainAppnameimage: us-central1-docker.pkg.dev/or2-msq-epm-cedu-t1iylu/petclinic-repo-halka/petclinic-app
mainAppnameimagetag: latest
sidecarAppname: cloud-sql-proxy
sidecarAppnameimage: gcr.io/cloudsql-docker/gce-proxy
sidecarAppnameimagetag: 1.28.0
replicaCount: 1
servicePort: 80
serviceTargetPort: 8080
serviceType: LoadBalancer